image: jdrouet/docker-with-buildx:latest

variables:
  #DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:dind

build:
  stage: build
  script:
    - ./build_docker.sh
